<?php 
$rows=$viewParams['rows'];
?>
 <div class="table-responsive">	            
<a href="/user/insert">Insert</a>
<table class="table table-striped">
    <?php foreach ($rows as $key => $row):?>
    	<tr>
        	<?php foreach ($row as $data):?>
            	<td><?=$data;?></td>
            <?php endforeach;?>    
            <td>
                <a href="/user/update/id/<?=$row['iduser'];?>">Update</a> |
                <a href="/user/delete/id/<?=$row['iduser'];?>">Delete</a>       
            </td>    
        </tr>
    <?php endforeach;?>
</table>
</div>
        
        
        